create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text,
  category text,
  description text,
  image_url text,
  eco_score integer check (eco_score >= 0 and eco_score <= 100),
  materials text,
  created_at timestamptz not null default now()
);

create table if not exists public.prices (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  platform text not null,
  price numeric(10, 2) not null check (price >= 0),
  discount integer not null default 0 check (discount >= 0 and discount <= 100),
  product_url text,
  availability text not null default 'In Stock',
  unique (product_id, platform)
);

create table if not exists public.eco_metrics (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  carbon_footprint numeric(10, 2),
  water_usage numeric(10, 2),
  recyclability integer check (recyclability >= 0 and recyclability <= 100),
  unique (product_id)
);

create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id text not null,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create index if not exists idx_products_category on public.products(category);
create index if not exists idx_products_eco_score on public.products(eco_score);
create index if not exists idx_prices_product_id on public.prices(product_id);
create index if not exists idx_prices_platform on public.prices(platform);
create index if not exists idx_wishlist_user_id on public.wishlist(user_id);

alter table public.products enable row level security;
alter table public.prices enable row level security;
alter table public.eco_metrics enable row level security;
alter table public.wishlist enable row level security;

drop policy if exists "public read products" on public.products;
create policy "public read products"
on public.products
for select
to anon, authenticated
using (true);

drop policy if exists "public read prices" on public.prices;
create policy "public read prices"
on public.prices
for select
to anon, authenticated
using (true);

drop policy if exists "public read eco metrics" on public.eco_metrics;
create policy "public read eco metrics"
on public.eco_metrics
for select
to anon, authenticated
using (true);

drop policy if exists "public manage wishlist" on public.wishlist;
create policy "public manage wishlist"
on public.wishlist
for all
to anon, authenticated
using (true)
with check (true);
